#ifndef RepositoryForExpressions
#define RepositoryForExpressions
#include <map>
#include <string>

std::map<std::string, std::string> myMap = {
	// grammar
	/*
	{ "galin svali dosta kilogrami prez poslednite nqkolko meseca<PreP>" , "Galin has lost a lot of weight in the last few months" },
	{ "jana otdavna ne se e podstrigvala<PreP>" , "Jana hasn't cut her hair for a long time" },
	{ "vinagi sym obichal kartofi<PreP>" , "I've always liked potatoes" },
	{ "otkoga si aktior<PreP>" , "How long have you been an actor" },
	{ "vijdal li si nqkoga golqm vodopad<PreP>" , "Have you ever seen a big waterfall" },
	{ "vlakat se razvali tri pyti do sega<PreP>" , "The train has broken down three times so far" },
	{ "kris zakysnqva za wtori pyt<PreP>" , "Chris has been late for the second time" },
	{ "tova e nai_hubaviqt prysten koito nqkoga sym vijdal<PreP>" , "This is the most beautiful ring I have ever seen" },
	{ "platih ti taksata<PreP>" , "I have paid you the tax" },
	{ "tq mu e pratila imeil<PreP>" , "She has sent him an email" },
	{ "kogato pristignahme chasyt beshe zapochanl<PastP>" , "When we arrived the class had started" },
	{ "napisah si domashnoto predi Maik da se pribere<PastP>" , "I had finished my homework before Mike came home" },
	{ "iska mi se da bqhme otsednali v drug hotel<PastP>" , "I wish we had stayed at another hotel" },
	{ "iska ni se da bqhme pomolili za pomosht po-rano" , "We wish we had asked for help earlier" },
	{ "beshe li zapochnal chasa <PastP>" , "Had the class started" },
	{ "beshe li zapochnal chasa <PastP>" , "Had you finished your homework" },
	{ "jivql li e georgi vyv varna predi da se premesti v sofia<PastP>" , "Had Georgi lived in Varna before he moved to Sofia" },
	{ "kak povredi koleloto<PastP>" , "How had you damaged the bike" },
	{ "za da ni osvobodi ot tova breme"  ,  "to relieve us of that burden" },
	{ "ako bqh prezident na kompaniqta shtqh da napravq mnogo promeni" , "If I were the president of company I would make a lot of changes." },
	{ "shtqh da si kupq nova kola, ako imah pari"  ,  "i would buy a new car if I had the money" },
	{ "mojem da porychame pica tazi vecher"  ,  "we could order pizza tonight" },
	{ "Bqh chakal poveche ot edin chas, kogato vlakyt pristigna"  ,  "I had been waiting for more than an hour when the train arrived" } ,
	{ "Ne bqh chakal poveche ot edin chas, kogato vlakyt pristigna"  ,  "I had not been waiting for more than an hour when the train arrived" } ,
	{ "Chaka li mnogo predi da doide vlakyt?"  ,  "Had you been waiting for long before the train arrived?" } ,
	{ "Ivan i Petyr igraha futbol dva chasa predi da se umorqt"  ,  "Ivan and Petar had been playing football for two hours before they got tired" } ,
	{ "ne beshe uchila mnogo za nego" , "She had not been studying much for it" } ,
	{ "Bobi postoqnno zakysnqvashe za rabota zashtoto hodeshe mnogo na partita"  ,  "Bobi was constantly late for work because he had been partying a lot" } ,
	{ "Az samo si mechtaeh da otida v london predi da se poqvish"  ,  "I had only been dreaming to go to London before you came up" } ,
	{ "bih iskal da go vidq"  ,  "i'd like to see it" } ,
	{ "John i Rosi snoshti otidoha na teatyr"  ,  "John and Rossy went to the theater last night" } ,
	{ "Vremeto beshe ujasno"  ,  "The weather was horrible" } ,
	{ "Lili vinagi mi se obajdashe v petycite"  ,  "Lily always rang me on Fridays" } ,
	{ "Koga si roden?"  ,  "When were you born?" } ,
	{ "Ne valq"  ,  "It didn’t rain" } ,
	{ "Ne nosehme podhodqshti drehi"  ,  "We didn’t wear appropriate clothes" } ,
	{ "Predade li i kliuchovete?"  ,  "Did you give her the keys?" } ,
	{ "izpylnenie"  ,  "implementation" },
	{ "osven towa","besides"   },
	{ "Zaslujava da se otbeleji","it's worth noting"  },
	{ "kub kuhini"  ,  "bunch of cubbyholes"  },
	{ "izvlichane"  ,  "retrieve"  },
	{ "sledovatelno"  ,  "therefore"  },
	{ "prenebrejimo"  ,  "negligible"  },
	{ "vse po-dosadno"  ,  "increasingly tedious" },
	{ "nqma li da e hubavo"  ,  "wouldn't it be nice" },
	{ "ot vreme na vreme"  ,  "occasionally" },
	{ "kydeto ni trqbvat"  ,  "wherever we need them" },
	{ "ti/vie shte trqbva"  ,  "you would have to" },

	*/
	/*
	{ "podrejdane"  ,  "arranging" },
	{ "dali"  ,  "whether" },
	{ "sravneniq"  ,  "comparisons" },
	{ "izvikan"  ,  "invoked" },
	{ "razpada"  ,  "decay" },
	{ "ako iskash"  ,  "if you would like to" },
	{ "ne sym besen/lud"  ,  "i'm not mad" },
	{ "okazva se"  ,  "it turns out" },
	{ "taka che vypreki"  ,  "so even though" },
	{ "sposobnost"  ,  "capability" },
	{ "umishleno"  ,  "intentional" },
	{ "osobeno"  ,  "particularly" },
	{ "vinagi kogato se zanimavate"  ,  "whenever you are dealing" },
	{ "ti/vie trqbva"  ,  "you should" },
	{ "propusnat"  ,  "omitted" },
	{ "kolkoto i stranno"  ,  "strangely enough" },
	{ "sblysak !collision"  ,  "encounter" },
	{ "tyrseneto"  ,  "demand" },
	{ "chrez tozi instrumen"  ,  "through this tool" },
	{ "prispadane"  ,  "deduction" },
	{ "nelovko"  ,  "awkward" } ,
	{ "osnovno preduprejdenie"  ,  "major caveat" },
	{ "sybitiq"  ,  "occurrences" },
	{ "psevdonim"  ,  "alias" },
	{ "vypreki che"  ,  "even though" },
	{ "prepovqdvane"  ,  "preaching" },
	{ "da zavyrja"  ,  "to tie" },
	{ "zashto bih iskal"  ,  "why would I want" },
	{ "ubejdavam te"  ,  "convince you" },
	{ "blagodarnost"  ,  "gratitude" },
	{ "stranno"  ,  "weird" },
	{ "atentat"  ,  "assassinate" },
	{ "pregrydka"  ,  "embrase" },
	{ "stegni se"  ,  "brace yourself" },
	{ "namereniq"  ,  "intentions" },
	{ "i kakvo ot tova"  ,  "so what" },
	{ "subekti"  ,  "entities" },
	{ "gostopriemstvo"  ,  "hospitality" },
	{ "nadcenqva"  ,  "overestimate" },
	{ "podcenqva"  ,  "underestimate" },
	{ "obobshtenie"  ,  "recap" },
	{ "sravnitelno"  ,  "comparatively" },
	{ "zakluchenie"  ,  "conclusion" },
	{ "izkushavashto"  ,  "tempting" },
	{ "posledstviq"  ,  "consequences" },
	{ "bybriv"  ,  "chaty" },
	{ "chudo"  ,  "miracle" },
	{ "predpolagam"  ,  "assume" },
	{ "jalyk"  ,  "pathetic" },
	{ "dostatuchno"  ,  "sufficient" },
	{ "udobstvo"  ,  "convenience" },
	{ "jaden"  ,  "thirsty" },
	{ "makar che"  ,  "although" },
	{ "razlichavam"  ,  "distinguish" },
	{ "izhvyrleni"  ,  "discarded" },
	{ "predlojeniq"  ,  "assumptions" },
	{ "znachitelno"  ,  "vastly" },
	{ "zanchitelen"  ,  "significant" },
	{ "veselo"  ,  "hilarious" },
	{ "kakto i da e "  ,  "whatever" },
	{ "otvlichane"  ,  "kidnap" },
	{ "sporazumenie"  ,  "agreement" },
	{ "belejit"  ,  "notable" },
	{ "razdraznitelen"  ,  "irritable" },
	{ "za shtastie"  ,  "fortunately" },
	{ "izdryjlivost"  ,  "endurance" },
	{ "prizvanie"  ,  "vocation" },
	{ "kovaren chovek"  ,  "conniving man" },
	{ "povod"  ,  "occasion" },
	{ "krainici"  ,  "limbs" },
	{ "maniq"  ,  "obsession" },
	{ "otvratitelno"  ,  "disgusting" },
	{ "vkluchvat !involve"  ,  "include" },
	{ "vkluchvat !include"  ,  "involve" },
	{ "imal predvid"  ,  "meant" },
	{ "pregovarqm"  ,  "negotiate" },
	{ "prednaznachenie"  ,  "purpose" },
	{ "uqzvimost"  ,  "vulnerability" },
	{ "shtedrost"  ,  "generosity" },
	{ "uveren"  ,  "assured" },
	{ "chestno kazano"  ,  "honestly" },
	{ "priznai"  ,  "admit" },
	{ "sblysuk !encounter"  ,  "collision" },
	{ "uchastvat"  ,  "participate" },
	{ "predlagam ti"  ,  "I suggest you" },
	{ "grub"  ,  "rude" },
	{ "iznudvane"  ,  "blackmailing" },
	{ "zabluda"  ,  "delusion" },
	{ "vutreshno"  ,  "internally" },
	{ "bezbroi"  ,  "myriad" },
	{ "nashiqt grob"  ,  "our grave" },
	{ "neizvesnost"  ,  "obscurity" },
	{ "otlychvane"  ,  "excommunication" },
	{ "kato ima predvid"  ,  "whereas" },
	{ "razlichen"  ,  "distinct" },
	{ "osven tova"  ,  "furthermore" },
	{ "sledovatelno"  , "therefore"},
	{ "prednaznachenie"  ,  "dedicated" },
	{ "po-natatyk"  ,  "further" },
	{ "periferni ustroistva"  ,  "peripherals" },
	{ "nezavisimo"  ,  "regardless" },
	{ "predpriqtie"  ,  "enterprise" },
	{ "okolen svqt/obkryjenie"  ,  "environment" },
	{ "nezavisimo"  ,  "regardless " },
	{ "energonezavisim"  ,  "non volatile" },
	{ "obijdam"  ,  "insult" },
	{ "vduhnovqvashto"  ,  "inspiring" },
	{ "zavladqvashto"  ,  "gripping" },
	{ "doprinese"  ,  "contributed" },
	{ "ochevidno !obvious"  ,  "apparently" },
	{ "uvajavam"  ,  "look up to" },
	{ "nadejden, moje da se razchita"  ,  "dependable" },
	{ "otglejdam"  ,  "bring up" },
	{ "ednovremenen dostyp"  ,  "concurrent access" },
	{ "razmeneni"  ,  "exchanged" },
	{ "dql"  ,  "partition" },
	{ "bez zakysnenie"  ,  "no delay" },
	{ "uverqvam"  ,  "to ensure" },
	{ "mojesh li da razberesh"  ,  "can you figure out" },
	{ "poddyrjam vryzja"  ,  "keep in touch" },
	{ "gubq vryzka"  ,  "lose touch" },
	{ "skarvam se"  ,  "fall out" },
	{ "opoznavam q"  ,  "get to know her" },
	{ "prinadleja na"  ,  "belong to" },
	{ "gubq samoobladanie"  ,  "lose temper" },
	{ "sklonen kym kompromisi"  ,  "tend to compromises" },
	{ "revniv"  ,  "jealous" },
	{ "osnovavam"  ,  "found" },
	{ "ship"  ,  "spike" },
	{ "kradq !steal"  ,  "rob" },
	{ "rykovodstvo"  ,  "guide" },
	{ "koncentraciq"  ,  "concentration" },
	{ "vnimanie"  ,  "attention" },
	{ "disciplina"  ,  "discipline" },
	{ "ako mi dadete vyzmojnost"  ,  "if you give me the opportunity" },
	{ "poluchavam instrukcii"  ,  "get directions" },
	{ "harduerno oformlenie"  ,  "hardware layout" },
	{ "nadvishava"  ,  "exceed" },
	{ "kolebliv"  ,  "vacillate" },
	{ "nabliudatelen"  ,  "observ" },
	{ "nadqvam se"  ,  "I hope" },
	{ "predizvikvam te"  ,  "I dare you" },
	{ "davq se"  ,  "drown" },
	{ "otstypvame"  ,  "we retreat" },
	{ "nai-chesto"  ,  "most often" },
	{ "trqbva da go inicializiram"  ,  "I need to initialize" },
	{ "za men beshe predizvikatelstvo"  ,  "it was a challenge for me" },
	{ "lubopitno"  ,  "curious" },
	{ "akcentirah vyrhu"  ,  "I focused on" },
	{ "po-golqmo"  ,  "any bigger" },
	{ "podslon"  ,  "shelter" },
	{ "nedostatychno"  ,  "insufficient" },
	{ "trqbva da osvobodq pametta"  ,  "I have to deallocate memory" },
	{ "Shte vi pokaja"  ,  "I'm going to show you" },
	{ "predpolagam !suppose"  ,  "I guess" },
	{ "predpolagam !guess"  ,  "I suppose" },
	{ "obiknovenni !regular"  ,  "ordinary" },
	{ "udovletvorq vashite iziskvaniq"  ,  "meets your requirements" },
	{ "povtarqshti se modeli"  ,  "recurring patterns" },
	{ "stradat"  ,  "suffer" },
	{ "jaltk !pathetic"  ,  "miserable" },
	{ "sys sigurnost trqbva da se nauchi"  ,  "certainly have to learn" },
	{ "sa bili"  ,  "awere" },
	{ "poshtaden"  ,  "spared" },
	{ "obhvashta ot"  ,  "spans from" },
	{ "kritichen nedostatyk" , "critical flaw" },
	{ "bezvreden" , "harmless" },
	{ "karam se na"  ,  "tell someone off" },
	{ "metnal sym se"  ,  "take after" },
	{ "grija se"  ,  "look after" },
	{ "skoroshen"  ,  "recent" },
	{ "jica,kabel"  ,  "wire" },
	{ "nejelan"  ,  "undesirable" },
	{ "nerealen"  ,  "unrealistic" },
	{ "ne stava za gledane"  ,  "unwatchable" },
	{ "bezmisleno"  ,  "nonsense" },
	{ "spotaivash,promykva,debne" , "lurking" },
	{ "prichinqvam"  ,  "cause" },
	{ "spasqvam"  ,  "rescue" },
	{ "kranche"  ,  "tap" },
	{ "kyrpa"  ,  "towel" },
	{ "otivam na pochivka"  ,  "go on holiday" },
	{ "izvyrshvam samoubistvo"  ,  "commit a suicide" },
	{ "razvivam ideq"  ,  "develop an idea" },
	{ "prichinqvam nepriqtnosti"  ,  "cause trouble" },
	{ "porta"  ,  "gate" },
	{ "jilishten raion"  ,  "residential area" },
	{ "lesen za realizaciq"  ,  "easy to implement in" },
	{ "negostopriemen"  ,  "unwelcoming" },
	{ "sgyvam"  ,  "fold" },
	{ "domakinstvo"  ,  "household" },
	{ "zavyrshvam s tazi zadacha' i krai"  ,  "end up with that task" },
	{ "svyrshvam vremeto"  ,  "run out of time" },
	{ "klimatik"  ,  "air conditioner" },
	{ "ne si struva"  ,  "it's not worth" },
	{ "struva si vremeto"  ,  "good value for time" },
	{ "kradec"  ,  "burglar" },
	{ "osnovna prichina !major reason" , "underlying reason" },
	{ "davam pari nazaem"  ,  "lend money" },
	{ "vreme na razpolojenie"  ,  "time for spare" },
	{ "vyshishtavam"  ,  "admire" },
	{ "mamq"  ,  "cheat" },
	{ "izmislqm si"  ,  "make up" },
	{ "navaksvam"  ,  "catch up with" },
	{ "ne trqbva da govorish"  ,  "you shouldn't speak" },
	{ "ambicii"  ,  "ambitious" },
	{ "uveren"  ,  "confident" },
	{ "grandomaniq"  ,  "extravagant" },
	{ "toleranten"  ,  "tolerant" },
	{ "razshirqvam,uvelichavam"  ,  "expand" },
	{ "avantiura/riskovano nacinanie"  ,  "venture" },
	{ "kasa"  ,  "checkout" },
	{ "kasova belejka"  ,  "receipt" },
	{ "svyrshvam"  ,  "run out of" },
	{ "izoliram"  ,  "insulate" },
	{ "obajdaniq"  ,  "appels" },
	{ "privlicha"  ,  "appeal" },
	{ "iskam da kaja"  ,  "I mean" },
	{ "zaradi"  ,  "because of" },
	{ "reshen sym !dedicated"  ,  "I am determined" },
	{ "posveten !determined" , "dedicated"},
	{ "svyrzano s" , "associated with" },
	{ "po-podhodqshti" , "more relevant" },
	{ "predpochitam tova"  ,  "I'd rather that" },
	{ "suvpadenie/sluchainost"  ,  "coincidence" },
	{ "moje da e prilojenie"  ,  "might be application" },
	{ "veroqtno !probably"  ,  "likely" },
	{ "se prilaga"  ,  "applies" },
	{ "hapliv,ostyr"  ,  "poignant" },
	{ "otpadam"  ,  "drop out of" },
	{ "prodyljavam"  ,  "carry on" },
	{ "razbiram se dobre s"  ,  "get on well with" },
	{ "staranie"  ,  "diligence" },
	{ "postoqnstvo"  ,  "perseverance" },
	{ "vgradeni ustroistva"  ,  "incorporated devices" },
	{ "nereshitelen"  ,  "indecisive" },
	{ "neizbejno"  ,  "inevitable" },
	*/
	{ "nepronicaem"  ,  "impenetrable" },
	{ "otgovarq na usloviqta"  ,  "eligible" },
	{ "predgradiq"  ,  "suburbs" },
	{ "vzaimodeistva" , "interfaces" },
	{ "v kraina smetka" , "ultimately" },
	{ "nevolno,bez da iskam" , "unintentionally" },
	{ "predimstvena prichina" , "precedence reasons" },
	{ "parche pamet !part" , "chunk of memory" },
	{ "bezkraino" , "infinitely" },
	{ "bih predpochel" , "I would prefer" },
	{ "opredeleno kolichestvo" , "a certain amount" },
	{ "zloupotreba" , "misuse" },
	{ "opredelen sluchai" , "certain case" },
	{ "leko neefektiven" , "slightly inefficient" },
	{ "syjitelstvat/syvmestno syshtestvuvavne" , "coexist" },
	{ "ne pokazvat dobyr stil !show" , "not exhibit good style" },
	{ "prepokrivane" , "overlapping" },
	{ "razchitam na" , "rely on" },
	{ "namalqva veroqtnostta" , "reduces the probability" },
	{ "te narushavat konstantnostta" , "they violate the constness" },
	{ "e neqsno" , "It's unclear" },
	{ "otricanie >>!<<" , "negation" },
	{ "predstavka" , "prefix" },
	{ "nastavka" , "postfix" },
	{ "shiroko" , "widely" },
	{ "predvidi" , "anticipate" },
	{ "napredyk" , "progress" },
	{ "malko poddryjka" , "low-maintenance" },
	{ "dobyr za izolaciq" , "good for insulating" },
	{ "nedostypno" , "Inaccessible" },
	{ "osobenni sluchai, chastni sluchai !certain" , "particular case" },
	{ "po-tochno !more clear" , "more accurate" },
	/*
	{ "" , "" },
	{ "" , "" },
	{ "" , "" },
	{ "" , "" },
	{ "" , "" },
	{ "" , "" },
	{ "" , "" },
	{ "" , "" },
	*/
};

#endif // !RepositoryForExpressions

